version: '3'
services:
  app:
    build: ./docker/build/php
    container_name: ${DOCKER_NAME}-app
    volumes:
      - .:/var/www

  queue:
    build: ./docker/build/php-queue
    container_name: ${DOCKER_NAME}-queue
    volumes:
      - .:/var/www

  mariadb:
    image: mariadb:latest
    container_name: ${DOCKER_NAME}-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=thisisareallystrongpassword123
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command:
      'mysqld --innodb-flush-method=fsync'

  nginx:
    build: ./docker/build/nginx
    container_name: ${DOCKER_NAME}-nginx
    ports:
      - 127.0.0.1:${DOCKER_HTTP_PORT}:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx-log:/var/log/nginx
      - .:/var/www

  phpmyadmin:
    container_name: ${DOCKER_NAME}-pma
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - 127.0.0.1:${DOCKER_PMA_PORT}:80
    environment:
      - PMA_HOST=mariadb

  mailhog:
    container_name: ${DOCKER_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:${DOCKER_MAILHOG_PORT}:8025