version: '3'
services:
    laravel.test:
        container_name: '${SAIL_CONTAINER_NAME}-app'
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                NODE_VERSION: '${NODE_VERSION}'
        image: '${SAIL_CONTAINER_NAME}/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${SAIL_APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mariadb
            - mailhog
    mariadb:
        container_name: '${SAIL_CONTAINER_NAME}-mariadb'
        image: 'mariadb:10'
        ports:
            - '${SAIL_SQL_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'thisisareallystrongpassword123'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mailhog:
        container_name: '${SAIL_CONTAINER_NAME}-mailhog'
        image: 'mailhog/mailhog:latest'
        ports:
            - '${SMTP_PORT:-1025}:1025'
            - '${SAIL_MAILHOG_PORT:-8025}:8025'
        networks:
            - sail
    phpmyadmin:
        container_name: '${SAIL_CONTAINER_NAME}-pma'
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '${SAIL_PMA_PORT}:80'
        environment:
            - 'PMA_HOST=mariadb'
            - 'PMA_PORT=${SAIL_SQL_PORT}'
            - 'UPLOAD_LIMIT=500M'
        networks:
            - sail
        depends_on:
            - mariadb
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
