name: 📌 Assign Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign issues/pull-requests to project
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: 'https://github.com/saproto/projects/1'
          github-token: ${{ secrets.PROJECTS_TOKEN }}
