name: ⚙ Deploy Check

on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Check
    runs-on: ubuntu-latest
    env:
      BUILD_SOURCE_DIR: .
      BUILD_ARTIFACT_STAGING_DIR: build/
      BUILD_ARTIFACT_DESTINATION_DIR: /domains/proto.utwente.nl/deployment/uploads/
      HOST_SERVER: s176.webhostingserver.nl
      SENTRY_ORG: sa-proto
      SENTRY_PROJECT: sa-proto-website
    steps:
      - name: 🛎️ Checkout project
        uses: actions/checkout@v3

      - name: 🔍 Read .env
        run: grep -E 'PHP_VERSION|NODE_VERSION' .env.prod >> $GITHUB_ENV

      - name: 🖱️ Setup PHP v${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - uses: ramsey/composer-install@v3
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"

      - name: 🖱️ Set Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: 📥 Install front-end dependencies
        run: npm ci --ignore-scripts

      - name: 🔨 build front-end
        run: npm run build

      - name: 🗑️ Remove storage directory
        run: rm -rf storage

      - name: 📝 Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ env.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
        with:
          environment: production
