name: ⚙ Deploy Check

on:
  push:
    branches-ignore:
      - master
      - vimexx

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Check
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout project
        uses: actions/checkout@v3

      - name: 🔍 Read .env
        run: grep -E 'PHP_VERSION|NODE_VERSION' .env.prod >> $GITHUB_ENV

      - name: 🖱️ Setup PHP v${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - uses: ramsey/composer-install@v3
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"

      - name: 🖱️ Set Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: 📥 Install front-end dependencies
        run: npm ci --ignore-scripts

      - name: 🔨 build front-end
        run: npm run build

      - name: 🗑️ Remove storage directory
        run: rm -rf storage
