name: 🛠 Format
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    name: 🛠 Fix PHP formatting
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: 🔍 Read .env
        run: grep -E 'PHP_VERSION' .env.prod >> $GITHUB_ENV

      - uses: ramsey/composer-install@v3

      - uses: actions/cache@v3
        with:
          path: .tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - run: mkdir -p .tmp/rector

      - name: Run rector
        run: vendor/bin/rector --ansi

      - name: Cache Pint
        uses: actions/cache@v3
        with:
          path: .tmp/pint.cache
          key: ${{ runner.os }}-pint-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-pint-

      - run: mkdir -p .tmp/pint

      - name: Run pint
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
